#ifndef __GIRAFFE_PAXOS_PACKETS_H__
#define __GIRAFFE_PAXOS_PACKETS_H__
#include "PGRFPaxosEventPkt.h"
#include "PGRFPaxosLeaderKeepAliveReq.h"
#include "PGRFPaxosLeaderKeepAliveRes.h"
#include "PGRFLeaderLocationReqPkt.h"
#include "PGRFLeaderLocationResPkt.h"
#include "PGRFBroadcastEventPkt.h"
#endif //__GIRAFFE_PAXOS_PACKETS_H__