#ifndef __GIRAFFE_COMMON_H__
#define __GIRAFFE_COMMON_H__

enum{
	LOCK_SHARE_MODE,
	LOCK_EXCLUSIVE_MODE,
	UNLOCKED_MODE,
};

enum{
	LOCK_STATUS_GRANTED,
	LOCK_STATUS_CONFLICTED,
};

#endif //__GIRAFFE_COMMON_H__